### PR TITLE
Added a project Tindog for the hacktoberfest.

### PR DESCRIPTION
**Pull request by Git-Akshat01**
Added a project Tindog which is tinder for dogs.

It is created using HTML, CSS, Bootstrap and is very user friendly and is very interesting to learn.

Hope to get the project accepted.

### CODE REVIEW

**Comment by Git-Akshat01** [comment]
Thanks @debrajrout

**Comment by Git-Akshat01** [comment]
Hey @debrajrout Please assign this issue to me as for a valid PR for hacktoberfest only a single person should be assigned a task/issue.

**Comment by debrajrout** [comment]
Yaa sure

**Comment by debrajrout** [comment]
Go ahead

**Comment by Git-Akshat01** [comment]
Ya i had already done the PR and is merged also. In the assignes section my id should be there as the issue is solved. Then only a valid PR is made a/c to hacktoberfest rules.

**Pull request merged**
